# execute: docker compose up -d 
# debug: docker compose up --build 

version: '3.8'

services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - type: volume
        source: world-data
        target: /minecraft
      - type: bind
        source: ./mods
        target: /minecraft/mods
        read_only: true
    restart: always

volumes:
  world-data:
